inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/fhir_stu3_models/fhir/**/*'
    - 'lib/fhir_stu3_models/fluentpath/evaluate.rb'
    - 'lib/**/*.rake'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'bin/*'
Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
inherit_mode:
  merge:
    - Exclude
