inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/fhir_dstu2_models/fhir/**/*'
    - 'lib/fhir_dstu2_models/fluentpath/evaluate.rb'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'bin/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Enabled: false
