language: ruby
env:
  - TESTMEMORY=0 GCDELAY=2.0
rvm:
  - 2.4
  - 2.5
  - 2.6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
addons:
  code_climate:
    repo_token: 0230b3379581b30743b7b4355d7394e427648e604d19a2aba987956201eee290
before_install:
  - gem update --system
  - gem install bundler
