language: ruby
env:
  - TESTMEMORY=0 GCDELAY=2.0
rvm:
  - "2.2.7"
  - "2.3.7"
  - "2.4.4"
  - "2.5.1"
script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
addons:
  code_climate:
    repo_token: 0230b3379581b30743b7b4355d7394e427648e604d19a2aba987956201eee290
before_install:
  - gem update --system
  - gem update bundler
